//
//  CDProject+CoreDataClass.swift
//  TidyNotes
//
//  Created by Prizega Fromadia on 08/05/25.
//

import Foundation
import CoreData

@objc(CDProject)
public class CDProject: NSManagedObject {
    // This file is automatically generated by Xcode when you create the Core Data model
    // But we're implementing it manually here for illustration
}

// TidyNotes/Data/CoreData/Model/CDProject+CoreDataProperties.swift
import Foundation
import CoreData

extension CDProject {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CDProject> {
        return NSFetchRequest<CDProject>(entityName: "CDProject")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var color: String?
    @NSManaged public var icon: String?
    @NSManaged public var isDefault: Bool
    @NSManaged public var tasks: NSSet?
    
    // Convenience computed property to get tasks as array
    var taskArray: [CDTask] {
        let set = tasks ?? NSSet()
        return set.allObjects as? [CDTask] ?? []
    }
    
    // Convenience method for creating a new project
    static func createProject(in context: NSManagedObjectContext, project: ProjectEntity) -> CDProject {
        let cdProject = CDProject(context: context)
        cdProject.id = project.id
        cdProject.name = project.name
        cdProject.color = project.color
        cdProject.icon = project.icon
        cdProject.isDefault = project.isDefault
        
        return cdProject
    }
    
    // Add and remove task methods
    func addToTasks(_ task: CDTask) {
        let taskSet = self.tasks ?? NSSet()
        self.tasks = taskSet.adding(task) as NSSet
    }
    
    func removeFromTasks(_ task: CDTask) {
        let taskSet = self.tasks ?? NSSet()
        self.tasks = taskSet.removing(task) as NSSet
    }
}
