//
//  CDTask+CoreDataClass.swift
//  TidyNotes
//
//  Created by Prizega Fromadia on 08/05/25.
//

import Foundation
import CoreData

@objc(CDTask)
public class CDTask: NSManagedObject {
    // This file is automatically generated by Xcode when you create the Core Data model
    // But we're implementing it manually here for illustration
}

// TidyNotes/Data/CoreData/Model/CDTask+CoreDataProperties.swift
import Foundation
import CoreData

extension CDTask {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CDTask> {
        return NSFetchRequest<CDTask>(entityName: "CDTask")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var title: String?
    @NSManaged public var taskDescription: String?
    @NSManaged public var isPriority: Bool
    @NSManaged public var createdAt: Date?
    @NSManaged public var dueDate: Date?
    @NSManaged public var status: String?
    @NSManaged public var project: CDProject?
    
    // Convenience method for creating a new task
    static func createTask(in context: NSManagedObjectContext, task: TaskEntity, project: CDProject? = nil) -> CDTask {
        let cdTask = CDTask(context: context)
        cdTask.id = task.id
        cdTask.title = task.title
        cdTask.taskDescription = task.description
        cdTask.isPriority = task.isPriority
        cdTask.createdAt = task.createdAt
        cdTask.dueDate = task.dueDate
        cdTask.status = task.status.rawValue
        cdTask.project = project
        
        return cdTask
    }
}
